### ISSUE TITLE
Portal Público para ODA

### ISSUE THREAD

**Issue by cormaza** [cormaza/transmedical_proceso_base#3]
Basarse en el Ejemplo de las Ordenes de Ventas con su portal público

**Comment by nelio2120** [comment]
Bajo la reunión se solicita de primera parte que lo primero sera usar la funcionalidad de compartir proveniente de sale order hacia la ODA

Se requiere construir el portal para que se pueda visualizar lo podemos encontrar en l10n_ec_delivery_note
Se debe agregar los permisos (ir.rule)
nota: Usar portal.mixin, controlador, plantilla qweb, permisos para portal

**Comment by cormaza** [comment]
@nelio2120 Adjunto el video de la explicación

https://www.youtube.com/watch?v=seOcW4Urkn4
