### ISSUE TITLE
Envío por Correo de ODA, plantilla para adjuntar report

### ISSUE THREAD

**Issue by cormaza** [cormaza/transmedical_proceso_base#4]
Verificar como se hace en los pedidos de ventas, que se tiene una plantilla de correo que adjunta el formato impreso de la orden de venta, en este caso, el mismo de la ODA

**Comment by nelio2120** [comment]
En la reunión se explica que se requiere replicar la funcionalidad del envio de corre electronico de sale.order hacia ODA, mediante una plantilla generica
